### ISSUE TITLE
Could you share your Tensorflow frozen graph with us?

### ISSUE THREAD

**Issue by kissste** [chadwallacehart/aiy_custom_cat_detector#1]
Thank you very much for publishing the article and posting the code.

Could you share your Tensorflow frozen graph with us?
and, your SSD mobilenet v1 coco configuration that creates this network that fits the vision bonnet.
256x256 dw=0.125.

I would like to leverage your network and just to retrain last layer or so.

**Comment by chadwallacehart** [comment]
For retraining, I am happy to share my frozen graph, but I think you are better off using the one that @zhoujustin provided in [this issue](https://github.com/google/aiyprojects-raspbian/issues/314#issuecomment-389317428) -  https://drive.google.com/file/d/1_MeZ8kvmpNibPZvSJGnwKNRATeuyxNtu/view

That is based on the [20-class VOC dataset](http://host.robots.ox.ac.uk/pascal/VOC/).  That is what I trained from and is a better general purpose model to start from.

I attached mine for reference.  
[aiy_cat_detector_graph_v7.zip](https://github.com/chadwallacehart/aiy_custom_cat_detector/files/2108050/aiy_cat_detector_graph_v7.zip)
I don't think it help you much as a retraining point since it has been optimized for 2 my cats in my kitchen.

You will find a copy of the configuration file inside the zip.

**Comment by kissste** [comment]
Thank you very much.

**Comment by di-jabil** [comment]
Hi Chad, I am doing an object detection project following your blog [https://cogint.ai/custom-vision-training-on-the-aiy-vision-kit/](url). I ran into some issues. I posted an issue here [https://github.com/google/aiyprojects-raspbian/issues/563](url). I would much appreciate if you could take a look and give me some comments. Thank you so much

**Comment by chadwallacehart** [comment]
@di-jabil - I have not really spent much time on this project since I did the write-up in June 2018. I was hoping they would come up with an easier process or plug into Cloud-ML.

I looked at your [issue](https://github.com/google/aiyprojects-raspbian/issues/563) -it is not totally clear to me where you think you are having a problem. I haven't checked to see if they changed anything there since June, though I do see they have some new instructions here: https://aiyprojects.withgoogle.com/vision/#makers-guide--tensorflow-model-compiler

I would try that `EXTENSION TO POET TUTORIAL` first just to validate the Bonnet Compiler works in your environment.

I would also make sure you read through this issue: https://github.com/google/aiyprojects-raspbian/issues/314#issuecomment-389317428
